pull_request_rules:
  - name: label conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Automatic merge on approval
    conditions:
      - base=master
      - '#commits-behind=0'
      - or:
          - '#approved-reviews-by>=1'
          - label=ci:auto-merge
      - or:
          - head!=renovate/lock-file-maintenance
          - 'created-at<=24h ago'
      - check-success=cargo-lint-test
      - check-success=docker-build-check
      - check-success=pre-commit
    actions:
      merge:
        method: squash
